### ISSUE TITLE
Link to ssm-helpers broken

### ISSUE THREAD

**Issue by jhmartin** [disneystreaming/go-ssmhelpers#1]
The link to https://github.com/disneystreaming/go-ssmhelpers renders as https://github.com/disneystreaming/go-ssmhelpers/blob/master/github.com/disneystreaming/ssm-helpers , plus it does not appear to be a public project.

**Comment by rothgar** [comment]
Thanks, we're still working on open sourcing that repo which implements CLI tools on top of this library. I hope it'll be ready soon and we'll have an announcement blog post etc.

We'll make sure this works when the repo is made public.

**Comment by rothgar** [comment]
The repo is public now.
